site_name: Shift Framework
repo_url: https://github.com/ShiftSoftware/ShiftFrameworkDocs
repo_name: ShiftSoftware/ShiftFrameworkDocs
site_author: Shift Software
edit_uri: ShiftFrameworkDocs/edit/master/docs/
copyright: Copyright &copy; Shift Software
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - navigation.collapse
nav:
    - Home: 'index.md'
    - Project Setup:
        - Overview: 'project-setup/overview.md'
        - Shared Project:
            - Dependencies: 'project-setup/shared-project/dependencies.md'
            - DTOs:         'project-setup/shared-project/dtos.md'
            - Enums:        'project-setup/shared-project/enums.md'
            - Action Trees: 'project-setup/shared-project/action-trees.md'
        - Data Project:
            - Dependencies:             'project-setup/data-project/dependencies.md'
            - Entities :                'project-setup/data-project/entities.md'
            - AutoMapper Profiles:      'project-setup/data-project/auto-mapper-profiles.md'
            - DB Context:               'project-setup/data-project/db-context.md'
            - Migrations:               'project-setup/data-project/migrations.md'
            - Repositories:             'project-setup/data-project/repositories.md'
        
extra_css:
  - overrides/css/extra.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ShiftSoftware
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/shift.software
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/shift-software
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/the.shift.software

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.mark
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true