
site_name: Shift Framework
repo_url: https://github.com/ShiftSoftware/ShiftFrameworkDocs
repo_name: ShiftSoftware/ShiftFrameworkDocs
site_author: Shift Software
edit_uri: ShiftFrameworkDocs/edit/master/docs/
copyright: Copyright &copy; Shift Software
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - navigation.collapse
nav:
    - Home: 'index.md'
    - Project Setup:
        - Overview: 'project-setup/overview.md'
        - Shared Project:
            - Dependencies: 'project-setup/shared-project/dependencies.md'
            - DTOs:         'project-setup/shared-project/dtos.md'
            - Enums:        'project-setup/shared-project/enums.md'
            - Action Trees: 'project-setup/shared-project/action-trees.md'
        - Data Project:
            - Dependencies:             'project-setup/data-project/dependencies.md'
            - Entities :                'project-setup/data-project/entities.md'
            - AutoMapper Profiles:      'project-setup/data-project/auto-mapper-profiles.md'
            - DB Context:               'project-setup/data-project/db-context.md'
            - Migrations:               'project-setup/data-project/migrations.md'
            - Repositories:             'project-setup/data-project/repositories.md'
        - Test Project:
            - Dependencies:                               'project-setup/test-project/dependencies.md'
            - Test Case Orderer:                          'project-setup/test-project/test-case-orderer.md'
            - Custom Web Application Factory:             'project-setup/test-project/custom-web-application-factory.md'
            - Collection Fixture:                         'project-setup/test-project/collection-fixture.md'
        - API Project:
            - Dependencies:                               'project-setup/api-project/dependencies.md'
            - Setup & Configurations:                     'project-setup/api-project/setup-and-configurations.md'
            - Program.cs Example:                         'project-setup/api-project/program.cs.md'
        - Web Project:
            - Dependencies:                               'project-setup/web-project/dependencies.md'
            - Setup & Configurations:                     'project-setup/web-project/setup-and-configurations.md'
    - TypeAuth:
            - Intro: 'type-auth/intro.md'
    - Quick Start:
            - Create Data Project:                        'quick-start/create-data-project.md'
            - Create Entity:                              'quick-start/create-entity.md'
            - Create Shared Project:                      'quick-start/create-shared-project.md'
            - Create DTOs:                                'quick-start/create-dtos.md'
            - Create Automapper Profile:                  'quick-start/create-automapp-profile.md'
            - Create Repository:                          'quick-start/create-repository.md'
            - Create DB Context:                          'quick-start/dbcontext.md'
            - Create API Project:                         'quick-start/create-api-project.md'
            - Configure API Project:                      'quick-start/configure-api.md'
            - Create Migration:                           'quick-start/create-migration.md'
extra_css:
  - overrides/css/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ShiftSoftware
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/shift.software
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/shift-software
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/the.shift.software

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.mark
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true